/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'justinask' at '1/12/17 3:19 PM' with Gradle 3.1
 *
 * @author justinask, @date 1/12/17 3:19 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
